### ISSUE TITLE
Make co-organizers maintainers of this Github repo

### ISSUE THREAD

**Issue by s4b7r** [MADICES/MADICES-2025#7]
@edan-bainglass @ml-evs 

### Discussed in https://github.com/MADICES/MADICES-2025/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **s4b7r** and **[samikanza](https://github.com/samikanza)** November  4, 2024 to November 5</sup>
@s4b7r happy to stick minutes in here, should we make it an announcement rather than general though?

<sup>Originally posted by **s4b7r** and **[samikanza](https://github.com/samikanza)** November  4, 2024 to November 5</sup>
yes, making it an announcement would be nice but I think I dont have the permissions in the MADICES Github organization nor in this repo. I can't change the category to announcement. Do you have permissions? Otherwise maybe @edan-bainglass or @ml-evs can make us part of the organization or invite us properly to this repo? Would make sense for the future anyways, I guess.

</div>

**Comment by ml-evs** [comment]
I've just invited all organisers as admins of the organisation, you should get the invite over email
